version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=filmes-db      
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "changeme@email.com"
      PGADMIN_DEFAULT_PASSWORD: "changeme"
    ports:
      - "54321:80"
    depends_on:
      - postgres